---
- name: Loops
  hosts: ubuntu1
  become: yes

  tasks:
  - name: say hello to all
    debug: msg="Hello {{ item }}"
    loop: 
    - "Vasya"
    - "Petya"
    - "Oleg"

  - name: Using Until
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZZ") == false

  - name: print output
    debug: var=output.stdout

#  - name: install many programs
#    yum: name={{ item }} state=latest
#    loop:
#    - htop
#    - python
#    - mysql-client

...
